#pragma once
#define GAME_VERSION_MAJOR			0
#define GAME_VERSION_MINOR			1
#define GAME_VERSION_PATCH			0
#define GAME_BRANCH_NAME			GIT_BRANCH
#define GAME_VERSION				PACK_VERSION( GAME_VERSION_MAJOR, GAME_VERSION_MINOR, GAME_VERSION_PATCH )
#define GAME_VERSION_STRING			STRINGIFY( GAME_VERSION_MAJOR ) "." STRINGIFY( GAME_VERSION_MINOR ) "." STRINGIFY( GAME_VERSION_PATCH ) "-" GAME_BRANCH_NAME
