#include "tools/ecscompiler/ecscppgenerator.h"

// Table for convert ecsSystemStage_t to text
static const achar* s_pEcsSystemStageNames[] =
{
	"OnStart",			// ECS_SYSTEM_STAGE_ONSTART
	"OnLoad",			// ECS_SYSTEM_STAGE_ONLOAD
	"PostLoad",			// ECS_SYSTEM_STAGE_POSTLOAD
	"PreUpdate",		// ECS_SYSTEM_STAGE_PREUPDATE
	"OnUpdate",			// ECS_SYSTEM_STAGE_ONUPDATE
	"OnValidate",		// ECS_SYSTEM_STAGE_ONVALIDATE
	"PostUpdate",		// ECS_SYSTEM_STAGE_POSTUPDATE
	"PreStore",			// ECS_SYSTEM_STAGE_PRESTORE
	"OnStore"			// ECS_SYSTEM_STAGE_ONSTORE
};

/*
==================
CEcsCppGenerator::Generate
==================
*/
void CEcsCppGenerator::Generate( CEcsStubModule* pEcsStubModule, ecsCppFileType_t cppFileType )
{
	// Write header and include guard
	buffer +=  "//\n"
				"// This is automatically generated by the ecscompiler.\n"
				"// DO NOT modify this manually! Edit the corresponding .ecs files instead!\n"
				"// Broken Singularity, All Rights Reserved.\n"
				"//\n\n";
	switch ( cppFileType )
	{
	case ECS_CPP_FILE_TYPE_HEADER:		GenerateHeader( pEcsStubModule );	break;
	case ECS_CPP_FILE_TYPE_SOURCE:		GenerateSource( pEcsStubModule );	break;
	default:
		AssertMsg( false, "Unknown C++ file type 0x%X", cppFileType );
		break;
	}
}

/*
==================
CEcsCppGenerator::GenerateHeader
==================
*/
void CEcsCppGenerator::GenerateHeader( CEcsStubModule* pEcsStubModule )
{
	// Get include guard define name
	std::string		includeGuardDefineName;
	{
		std::string		moduleNameUpr = pEcsStubModule->GetName();
		S_Strupr( moduleNameUpr.data() );
		includeGuardDefineName = S_Sprintf( "__ECS_%s_H__", moduleNameUpr.c_str() );
	}

	buffer += S_Sprintf( "#ifndef %s\n", includeGuardDefineName.c_str() );
	buffer += S_Sprintf( "#define %s\n", includeGuardDefineName.c_str() );

	// Write usings
	GenerateUsings( pEcsStubModule->GetUsings() );

	// Write components
	GenerateStructs( pEcsStubModule->GetComponents(), ECS_STRUCT_TYPE_COMPONENT );
	GenerateStructs( pEcsStubModule->GetResources(), ECS_STRUCT_TYPE_RESOURCE );

	// Write systems
	GenerateSystems( pEcsStubModule->GetSystems() );

	// Write registrar of the module
	GenerateRegistrar( pEcsStubModule );

	// Write all data into the file
	buffer += S_Sprintf( "\n#endif // !%s", includeGuardDefineName.c_str() );
}

/*
==================
CEcsCppGenerator::GenerateSource
==================
*/
void CEcsCppGenerator::GenerateSource( CEcsStubModule* pEcsStubModule )
{
	// Generate implementation of EcsReadData functions to read a SENT data into an ECS structs
	GenerateImplementationEcsReadDataFuncs( pEcsStubModule );

	// Generate implementation of ECS factories
	GenerateImplementationEcsFactories( pEcsStubModule );
}

/*
==================
CEcsCppGenerator::GenerateUsings
==================
*/
void CEcsCppGenerator::GenerateUsings( const std::vector<TRefPtr<CEcsStubUsing>>& ecsStubUsings )
{
	if ( !ecsStubUsings.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN USING\n" );
		for ( uint32 usingIdx = 0, numUsings = ( uint32 )ecsStubUsings.size(); usingIdx < numUsings; ++usingIdx )
		{
			CEcsStubUsing*		pEcsStubUsing = ecsStubUsings[usingIdx];
			buffer += S_Sprintf( "#include \"%s\"\n", pEcsStubUsing->GetName() );
		}
		buffer += S_Sprintf( "// END USING\n" );
	}
}

/*
==================
CEcsCppGenerator::GenerateComponents
==================
*/
void CEcsCppGenerator::GenerateStructs( const std::vector<TRefPtr<CEcsStubDataType>>& ecsStubDataTypes, ecsStructType_t structsType )
{
	const achar*	pCppComment		= NULL;
	const achar*	pStructPrefix	= NULL;
	switch ( structsType )
	{
	case ECS_STRUCT_TYPE_COMPONENT:
		pCppComment		= "COMPONENTS";
		pStructPrefix	= "Component";
		break;

	case ECS_STRUCT_TYPE_RESOURCE:
		pCppComment		= "RESOURCES";
		pStructPrefix	= "Resource";
		break;

	default:
		AssertMsg( false, "Unknown struct type 0x%X", structsType );
	}

	if ( !ecsStubDataTypes.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN ECS %s\n", pCppComment );
		for ( uint32 dataTypeIdx = 0, numDataTypes = ( uint32 )ecsStubDataTypes.size(); dataTypeIdx < numDataTypes; ++dataTypeIdx )
		{
			CEcsStubDataType*										pEcsStubDataType			= ecsStubDataTypes[dataTypeIdx];
			const std::vector<TRefPtr<CEcsStubDefaultFieldValue>>&	ecsStubDefaultFieldValues	= pEcsStubDataType->GetDefaultFieldValues();
			const std::vector<TRefPtr<CEcsStubField>>&				ecsStubFields				= pEcsStubDataType->GetFields();
			bool													bDataTypeEmpty				= ecsStubDefaultFieldValues.empty() && ecsStubFields.empty();
			buffer += S_Sprintf( "struct ecs%s%s_t\n{", pStructPrefix, pEcsStubDataType->GetName() );
			
			// Write constructor
			if ( !ecsStubDefaultFieldValues.empty() )
			{
				buffer += S_Sprintf( "\n\tecs%s%s_t()\n", pStructPrefix, pEcsStubDataType->GetName() );
				for ( uint32 defaultFieldValueIdx = 0, numDefaultFieldValues = ( uint32 )ecsStubDefaultFieldValues.size(); defaultFieldValueIdx < numDefaultFieldValues; ++defaultFieldValueIdx )
				{
					CEcsStubDefaultFieldValue*		pEcsStubDefaultFieldValue = ecsStubDefaultFieldValues[defaultFieldValueIdx];
					buffer += S_Sprintf( "\t\t%s %s( %s )\n", defaultFieldValueIdx == 0 ? ":" : ",", pEcsStubDefaultFieldValue->GetName(), pEcsStubDefaultFieldValue->GetValue() );
				}
				buffer += "\t{}";
				if ( !ecsStubFields.empty() )
				{
					buffer += "\n";
				}
			}

			// Write fields
			for ( uint32 fieldIdx = 0, numFields = ( uint32 )ecsStubFields.size(); fieldIdx < numFields; ++fieldIdx )
			{
				CEcsStubField*		pEcsStubField			= ecsStubFields[fieldIdx];
				buffer += S_Sprintf( "\n\t%s %s;", pEcsStubField->GetType(), pEcsStubField->GetName() );
			}
			buffer += S_Sprintf( "%s};\n", !bDataTypeEmpty ? "\n" : "" );
			
			// Write component factories
			if ( structsType == ECS_STRUCT_TYPE_COMPONENT )
			{
				buffer += S_Sprintf( "IEcsComponentFactory* EcsCreateComponent%sFactory( const CSENTEntityDescComponent& sentComponent );\n", pEcsStubDataType->GetName() );
			}

			if ( dataTypeIdx + 1 < numDataTypes )
			{
				buffer += "\n";
			}
		}
		buffer += S_Sprintf( "// END ECS %s\n", pCppComment );
	}
}

/*
==================
CEcsCppGenerator::GenerateSystems
==================
*/
void CEcsCppGenerator::GenerateSystems( const std::vector<TRefPtr<CEcsStubSystem>>& ecsStubSystems )
{
	if ( !ecsStubSystems.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN ECS SYSTEMS\n" );
		for ( uint32 systemIdx = 0, numSystems = ( uint32 )ecsStubSystems.size(); systemIdx < numSystems; ++systemIdx )
		{
			CEcsStubSystem*									pEcsStubSystem = ecsStubSystems[systemIdx];
			std::string										updateParams;
			for ( uint32 fieldAccessType = 0; fieldAccessType < ECS_FIELD_NUM_ACCESS_TYPES; ++fieldAccessType )
			{
				const std::vector<TRefPtr<CEcsStubField>>&		fields = pEcsStubSystem->GetFields( ( ecsFieldAccessType_t )fieldAccessType );
				if ( fieldAccessType != 0 && !fields.empty() && !updateParams.empty() )
				{
					updateParams += ", ";
				}

				for ( uint32 fieldIdx = 0, numFields = ( uint32 )fields.size(); fieldIdx < numFields; ++fieldIdx )
				{
					CEcsStubField*		pField = fields[fieldIdx];
					switch ( fieldAccessType )
					{
					case ECS_FIELD_ACCESS_TYPE_READ:				updateParams += S_Sprintf( "const ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );											break;
					case ECS_FIELD_ACCESS_TYPE_WRITE:				updateParams += S_Sprintf( "ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );													break;
					case ECS_FIELD_ACCESS_TYPE_READ_OPTIONAL:		updateParams += S_Sprintf( "const ecsComponent%s_t* p%s", pField->GetType(), GetStringWithUpperFirstChar( pField->GetName() ).c_str() );	break;
					case ECS_FIELD_ACCESS_TYPE_READ_RESOURCE:		updateParams += S_Sprintf( "const ecsResource%s_t& %s", pField->GetType(), pField->GetName() );												break;
					case ECS_FIELD_ACCESS_TYPE_WRITE_OPTIONAL:		updateParams += S_Sprintf( "ecsComponent%s_t* p%s", pField->GetType(), GetStringWithUpperFirstChar( pField->GetName() ).c_str() );			break;
					case ECS_FIELD_ACCESS_TYPE_WRITE_RESOURCE:		updateParams += S_Sprintf( "ecsResource%s_t& %s", pField->GetType(), pField->GetName() );													break;
					default:
						AssertMsg( false, "Unknown field access 0x%X", fieldAccessType );
						break;
					}

					if ( fieldIdx + 1 < numFields )
					{
						updateParams += ", ";
					}
				}
			}

			buffer += S_Sprintf( "class CEcsSystem%s\n"
								 "{\n"
								 "public:\n"
								 "\tstatic void OnUpdate( CEcsWorld ecsWorld, ecsEntity_t entity%s );\n", 
								 pEcsStubSystem->GetName(), 
								 !updateParams.empty() ? S_Sprintf( ", %s", updateParams.c_str() ).c_str() : "" );
			buffer += S_Sprintf( "};\n" );
			if ( systemIdx + 1 < numSystems )
			{
				buffer += "\n";
			}
		}
		buffer += S_Sprintf( "// END ECS SYSTEMS\n" );
	}
}

/*
==================
CEcsCppGenerator::GenerateRegistrar
==================
*/
void CEcsCppGenerator::GenerateRegistrar( CEcsStubModule* pEcsStubModule )
{
	const std::vector<TRefPtr<CEcsStubDataType>>&		ecsStubComponents	= pEcsStubModule->GetComponents();
	const std::vector<TRefPtr<CEcsStubDataType>>&		ecsStubResources	= pEcsStubModule->GetResources();
	const std::vector<TRefPtr<CEcsStubSystem>>&			ecsStubSystems		= pEcsStubModule->GetSystems();
	
	buffer += "\n// Registrar of the module\n";
	buffer += S_Sprintf( "struct ecsModule%s_t\n"
						  "{\n"
						  "\tecsModule%s_t( flecs::world& flecsWorld )\n"
						  "\t{", pEcsStubModule->GetName(), pEcsStubModule->GetName() );

	// Register components
	if ( !ecsStubComponents.empty() )
	{
		buffer += "\n\t\t// Register components\n";
		buffer += "\t\tCEcsComponentTypes&\t\tecsComponentTypes = Game()->GetEcsComponentTypes();\n";
		for ( uint32 componentIdx = 0, numComponents = ( uint32 )ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
		{
			CEcsStubDataType*			pEcsStubComponent				= ecsStubComponents[componentIdx];
			CEcsStubMetadata*			pEcsStubComponentMetadata		= pEcsStubComponent->GetMetadata();
			CEcsStubMetadataValue*		pEcsStubComponentNameMetadata	= pEcsStubComponentMetadata ? pEcsStubComponentMetadata->GetValue( ECS_METADATA_TYPE_NAME ) : NULL;
			std::string					componentRegisterTypeName		= pEcsStubComponentNameMetadata && pEcsStubComponentNameMetadata->HasValue() ? pEcsStubComponentNameMetadata->GetValue() : "";
			if ( componentRegisterTypeName.empty() )
			{
				componentRegisterTypeName = pEcsStubComponent->GetName();
			}

			buffer += S_Sprintf( "\t\tflecsWorld.component<ecsComponent%s_t>();\n", pEcsStubComponent->GetName() );
			buffer += S_Sprintf( "\t\tecsComponentTypes.RegisterType( \"%s\", EcsCreateComponent%sFactory );\n", componentRegisterTypeName.c_str(), pEcsStubComponent->GetName() );
		}
	}

	// Register resources
	if ( !ecsStubResources.empty() )
	{
		buffer += "\n\t\t// Register resources\n";
		for ( uint32 resourceIdx = 0, numResources = ( uint32 )ecsStubResources.size(); resourceIdx < numResources; ++resourceIdx )
		{
			CEcsStubDataType*		pEcsStubResource = ecsStubResources[resourceIdx];
			buffer += S_Sprintf( "\t\tflecsWorld.component<ecsResource%s_t>();\n", pEcsStubResource->GetName() );
		}
	}

	// Register systems
	if ( !ecsStubSystems.empty() )
	{
		buffer += S_Sprintf( "\n\t\t// Register systems\n" );
		for ( uint32 systemIdx = 0, numSystems = ( uint32 )ecsStubSystems.size(); systemIdx < numSystems; ++systemIdx )
		{
			CEcsStubSystem*			pEcsStubSystem = ecsStubSystems[systemIdx];
			std::string				templateParams;
			std::string				readWriteFuncs;
			std::string				filterFuncs;
			std::string				updateParams;
			std::string				callUpdateParams;

			// Write template params and Flecs read/write functions
			for ( uint32 fieldAccessType = 0, globalFieldIdx = 0; fieldAccessType < ECS_FIELD_NUM_ACCESS_TYPES; ++fieldAccessType )
			{
				const std::vector<TRefPtr<CEcsStubField>>&		fields = pEcsStubSystem->GetFields( ( ecsFieldAccessType_t )fieldAccessType );
				if ( fieldAccessType != 0 && !fields.empty() && !updateParams.empty() )
				{
					templateParams		+= ", ";
					updateParams		+= ", ";
					callUpdateParams	+= ", ";
					readWriteFuncs		+= "\n";
				}

				for ( uint32 fieldIdx = 0, numFields = ( uint32 )fields.size(); fieldIdx < numFields; ++fieldIdx, ++globalFieldIdx )
				{
					CEcsStubField*		pField = fields[fieldIdx];
					switch ( fieldAccessType )
					{
					case ECS_FIELD_ACCESS_TYPE_READ:		
						updateParams		+= S_Sprintf( "const ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams		+= S_Sprintf( "const ecsComponent%s_t", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.read<ecsComponent%s_t>()", pField->GetType() );
						callUpdateParams	+= S_Sprintf( "%s", pField->GetName() );
						break;
					
					case ECS_FIELD_ACCESS_TYPE_READ_OPTIONAL:
					{
						std::string			fieldName = GetStringWithUpperFirstChar( pField->GetName() );
						updateParams		+= S_Sprintf( "const ecsComponent%s_t* p%s", pField->GetType(), fieldName.c_str() );
						templateParams		+= S_Sprintf( "const ecsComponent%s_t*", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.read<ecsComponent%s_t*>()", pField->GetType() );
						callUpdateParams	+= S_Sprintf( "p%s", fieldName.c_str() );
						break;
					}
					
					case ECS_FIELD_ACCESS_TYPE_READ_RESOURCE:		
						updateParams		+= S_Sprintf( "const ecsResource%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams		+= S_Sprintf( "const ecsResource%s_t", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.term_at( %i ).singleton()\n"
														  "\t\t\t.read<ecsResource%s_t>()", globalFieldIdx, pField->GetType() );
						callUpdateParams	+= S_Sprintf( "%s", pField->GetName() );
						break;

					case ECS_FIELD_ACCESS_TYPE_WRITE:	
						updateParams		+= S_Sprintf( "ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams		+= S_Sprintf( "ecsComponent%s_t", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.write<ecsComponent%s_t>()", pField->GetType() );
						callUpdateParams	+= S_Sprintf( "%s", pField->GetName() );
						break;
					
					case ECS_FIELD_ACCESS_TYPE_WRITE_OPTIONAL:
					{
						std::string			fieldName = GetStringWithUpperFirstChar( pField->GetName() );
						updateParams		+= S_Sprintf( "ecsComponent%s_t* p%s", pField->GetType(), fieldName.c_str() );
						templateParams		+= S_Sprintf( "ecsComponent%s_t*", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.write<ecsComponent%s_t*>()", pField->GetType() );
						callUpdateParams	+= S_Sprintf( "p%s", fieldName.c_str() );
						break;
					}

					case ECS_FIELD_ACCESS_TYPE_WRITE_RESOURCE:	
						updateParams		+= S_Sprintf( "ecsResource%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams		+= S_Sprintf( "ecsResource%s_t", pField->GetType() );
						readWriteFuncs		+= S_Sprintf( "\t\t\t.term_at( %i ).singleton()\n"
														  "\t\t\t.write<ecsResource%s_t>()", globalFieldIdx, pField->GetType() );
						callUpdateParams	+= S_Sprintf( "%s", pField->GetName() );
						break;
					
					default:
						AssertMsg( false, "Unknown field access 0x%X", fieldAccessType );
						break;
					}

					if ( fieldIdx + 1 < numFields )
					{
						templateParams		+= ", ";
						updateParams		+= ", ";
						callUpdateParams	+= ", ";
						readWriteFuncs		+= "\n";
					}
				}
			}
			if ( !readWriteFuncs.empty() )
			{
				readWriteFuncs += "\n";
			}

			// Write Flecs filters
			for ( uint32 systemFilterType = 0; systemFilterType < ECS_SYSTEM_NUM_FILTER_TYPES; ++systemFilterType )
			{
				const std::vector<TRefPtr<CEcsStubSystemFilter>>&		filters = pEcsStubSystem->GetFilters( ( ecsSystemFilterType_t )systemFilterType );
				if ( systemFilterType != 0 && !filters.empty() && !filterFuncs.empty() )
				{
					filterFuncs += "\n";
				}

				for ( uint32 filterIdx = 0, numFilters = ( uint32 )filters.size(); filterIdx < numFilters; ++filterIdx )
				{
					CEcsStubSystemFilter*	pEcsSystemFilter = filters[filterIdx];
					switch ( systemFilterType )
					{
					case ECS_SYSTEM_FILTER_TYPE_INCLUDE:		filterFuncs += S_Sprintf( "\t\t\t.with<ecsComponent%s_t>()", pEcsSystemFilter->GetName() );		break;
					case ECS_SYSTEM_FILTER_TYPE_EXCLUDE:		filterFuncs += S_Sprintf( "\t\t\t.without<ecsComponent%s_t>()", pEcsSystemFilter->GetName() );	break;
					default:
						AssertMsg( false, "Unknown system filter 0x%X", systemFilterType );
						break;
					}
				
					if ( filterIdx + 1 < numFilters )
					{
						filterFuncs += "\n";
					}
				}
			}
			if ( !filterFuncs.empty() )
			{
				filterFuncs += "\n";
			}

			// Register the system
			Assert( pEcsStubSystem->GetStage() < ARRAYSIZE( s_pEcsSystemStageNames ) );
			buffer += S_Sprintf( "\t\tflecsWorld.system<%s>()\n"
								 "\t\t\t.kind( flecs::%s )\n"
								 "%s"
								 "%s"
								 "\t\t\t.each( []( flecs::entity entity%s )\n"
								 "\t\t\t{\n"
								 "\t\t\t\tCEcsSystem%s::OnUpdate( entity.world(), entity%s );\n"
								 "\t\t\t} );\n", 
								 templateParams.c_str(), 
								 s_pEcsSystemStageNames[pEcsStubSystem->GetStage()], 
								 readWriteFuncs.c_str(), 
								 filterFuncs.c_str(),
								 !updateParams.empty() ? S_Sprintf( ", %s", updateParams.c_str() ).c_str() : "",
								 pEcsStubSystem->GetName(),
								 !callUpdateParams.empty() ? S_Sprintf( ", %s", callUpdateParams.c_str() ).c_str() : "" );
			if ( systemIdx + 1 < numSystems )
			{
				buffer += "\n";
			}
		}
	}

	buffer += "\t}\n};\n";
}

/*
==================
CEcsCppGenerator::GenerateImplementationEcsReadDataFuncs
==================
*/
void CEcsCppGenerator::GenerateImplementationEcsReadDataFuncs( CEcsStubModule* pEcsStubModule )
{
	const std::vector<TRefPtr<CEcsStubDataType>>&	ecsStubComponents = pEcsStubModule->GetComponents();
	for ( uint32 componentIdx = 0, numComponents = ( uint32 )ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
	{
		std::string									sentReadDataFields;
		CEcsStubDataType*							pEcsStubComponent	= ecsStubComponents[componentIdx];
		const std::vector<TRefPtr<CEcsStubField>>&	ecsStubFields		= pEcsStubComponent->GetFields();
		for ( uint32 varIdx = 0, numVars = ( uint32 )ecsStubFields.size(); varIdx < numVars; ++varIdx )
		{
			CEcsStubField*		pEcsStubField			= ecsStubFields[varIdx];
			CEcsStubMetadata*	pEcsStubFieldMetadata	= pEcsStubField->GetMetadata();
			if ( pEcsStubFieldMetadata && pEcsStubFieldMetadata->HasValue( ECS_METADATA_TYPE_SERIALIZE ) )
			{
				CEcsStubDefaultFieldValue*	pEcsStubDefaultFieldValue	= pEcsStubComponent->FindDefaultFieldValue( pEcsStubField->GetName() );
				CEcsStubMetadataValue*		pEcsStubFieldNameMetadata	= pEcsStubFieldMetadata->GetValue( ECS_METADATA_TYPE_NAME );
				std::string					fieldName					= pEcsStubFieldNameMetadata && pEcsStubFieldNameMetadata->HasValue() ? pEcsStubFieldNameMetadata->GetValue() : "";
				if ( fieldName.empty() )
				{
					fieldName = pEcsStubField->GetName();
				}

				if ( !sentReadDataFields.empty() )
				{
					sentReadDataFields += "\n\n";
				}

				sentReadDataFields += S_Sprintf( "\tCSENTEntityDescVar*\t\tpSENTVar_%s = sentComponent.GetVar( \"%s\" );\n", pEcsStubField->GetName(), fieldName.c_str() );
				sentReadDataFields += S_Sprintf( "\tif ( pSENTVar_%s )\n", pEcsStubField->GetName() );
				sentReadDataFields += "\t{\n";
				sentReadDataFields += S_Sprintf( "\t\tEcsReadData<%s>( component.%s, *pSENTVar_%s%s );\n",
												 pEcsStubField->GetType(), pEcsStubField->GetName(), pEcsStubField->GetName(),
												 pEcsStubDefaultFieldValue ? S_Sprintf( ", %s", pEcsStubDefaultFieldValue->GetValue() ).c_str() : "" );
				sentReadDataFields += "\t}";
				if ( pEcsStubDefaultFieldValue )
				{
					sentReadDataFields += "\n\telse\n";
					sentReadDataFields += "\t{\n";
					sentReadDataFields += S_Sprintf( "\t\tcomponent.%s = %s;\n", pEcsStubField->GetName(), pEcsStubDefaultFieldValue->GetValue() );
					sentReadDataFields += "\t}";
				}
			}
		}

		if ( !sentReadDataFields.empty() )
		{
			buffer += "/*\n";
			buffer += "==================\n";
			buffer += "EcsReadData\n";
			buffer += "==================\n";
			buffer += "*/\n";
			buffer += S_Sprintf( "static void EcsReadData( const CSENTEntityDescComponent& sentComponent, ecsComponent%s_t& component )\n"
								 "{\n"
								 "%s\n"
								 "}\n", 
								 pEcsStubComponent->GetName(), sentReadDataFields.c_str() );

			if ( componentIdx + 1 < numComponents )
			{
				buffer += "\n";
			}
		}
	}
}

/*
==================
CEcsCppGenerator::GenerateImplementationEcsFactories
==================
*/
void CEcsCppGenerator::GenerateImplementationEcsFactories( CEcsStubModule* pEcsStubModule )
{
	const std::vector<TRefPtr<CEcsStubDataType>>&		ecsStubComponents = pEcsStubModule->GetComponents();
	for ( uint32 componentIdx = 0, numComponents = ( uint32 ) ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
	{
		bool										bHasSerializableField	= false;
		CEcsStubDataType*							pEcsStubComponent		= ecsStubComponents[componentIdx];
		const std::vector<TRefPtr<CEcsStubField>>&	ecsStubFields			= pEcsStubComponent->GetFields();
		for ( uint32 varIdx = 0, numVars = ( uint32 ) ecsStubFields.size(); varIdx < numVars; ++varIdx )
		{
			CEcsStubField*		pEcsStubField			= ecsStubFields[varIdx];
			CEcsStubMetadata*	pEcsStubFieldMetadata	= pEcsStubField->GetMetadata();
			if ( pEcsStubFieldMetadata && pEcsStubFieldMetadata->HasValue( ECS_METADATA_TYPE_SERIALIZE ) )
			{
				bHasSerializableField = true;
				break;
			}
		}

		buffer += "/*\n";
		buffer += "==================\n";
		buffer += S_Sprintf( "EcsCreateComponent%sFactory\n", pEcsStubComponent->GetName() );
		buffer += "==================\n";
		buffer += "*/\n";
		buffer += S_Sprintf( "IEcsComponentFactory* EcsCreateComponent%sFactory( const CSENTEntityDescComponent& sentComponent )\n"
							 "{\n"
							 "\treturn new TEcsComponentFactory<ecsComponent%s_t, %s>( sentComponent );\n"
							 "}\n", 
							 pEcsStubComponent->GetName(), pEcsStubComponent->GetName(), bHasSerializableField ? "EcsReadData" : "NULL" );

		if ( componentIdx + 1 < numComponents )
		{
			buffer += "\n";
		}
	}
}