#include "tier0/iprofiler.h"
#include "tier0/ilogger.h"
#include "tools/ecscompiler/ecscppgenerator.h"

// Table for convert ecsSystemStage_t to text
static eastl::pair<const char*, const char*> s_pEcsSystemStageNames[] = {
	{ "on_start", "OnStart" },		  // ECS_SYSTEM_STAGE_ONSTART
	{ "on_load", "OnLoad" },		  // ECS_SYSTEM_STAGE_ONLOAD
	{ "post_load", "PostLoad" },	  // ECS_SYSTEM_STAGE_POSTLOAD
	{ "pre_update", "PreUpdate" },	  // ECS_SYSTEM_STAGE_PREUPDATE
	{ "on_update", "OnUpdate" },	  // ECS_SYSTEM_STAGE_ONUPDATE
	{ "on_validate", "OnValidate" },  // ECS_SYSTEM_STAGE_ONVALIDATE
	{ "post_update", "PostUpdate" },  // ECS_SYSTEM_STAGE_POSTUPDATE
	{ "pre_store", "PreStore" },	  // ECS_SYSTEM_STAGE_PRESTORE
	{ "on_store", "OnStore" }		  // ECS_SYSTEM_STAGE_ONSTORE
};
static_assert( ARRAYSIZE( s_pEcsSystemStageNames ) == ECS_SYSTEM_NUM_STAGES, "Size of s_pEcsSystemStageNames must be equal to ECS_SYSTEM_NUM_STAGES" );

// Table for convert profiler group to profileScopeGroup_t
static eastl::pair<const char*, const char*> s_pProfilerScopeGroupNames[] = {
	{ "none", "PROFILER_SCOPE_GROUP_NONE" },			  // PROFILER_SCOPE_GROUP_NONE
	{ "ai", "PROFILER_SCOPE_GROUP_AI" },				  // PROFILER_SCOPE_GROUP_AI
	{ "animation", "PROFILER_SCOPE_GROUP_ANIMATION" },	  // PROFILER_SCOPE_GROUP_ANIMATION
	{ "audio", "PROFILER_SCOPE_GROUP_AUDIO" },			  // PROFILER_SCOPE_GROUP_AUDIO
	{ "debug", "PROFILER_SCOPE_GROUP_DEBUG" },			  // PROFILER_SCOPE_GROUP_DEBUG
	{ "camera", "PROFILER_SCOPE_GROUP_CAMERA" },		  // PROFILER_SCOPE_GROUP_CAMERA
	{ "cloth", "PROFILER_SCOPE_GROUP_CLOTH" },			  // PROFILER_SCOPE_GROUP_CLOTH
	{ "gamelogic", "PROFILER_SCOPE_GROUP_GAMELOGIC" },	  // PROFILER_SCOPE_GROUP_GAMELOGIC
	{ "input", "PROFILER_SCOPE_GROUP_INPUT" },			  // PROFILER_SCOPE_GROUP_INPUT
	{ "navigation", "PROFILER_SCOPE_GROUP_NAVIGATION" },  // PROFILER_SCOPE_GROUP_NAVIGATION
	{ "network", "PROFILER_SCOPE_GROUP_NETWORK" },		  // PROFILER_SCOPE_GROUP_NETWORK
	{ "physics", "PROFILER_SCOPE_GROUP_PHYSICS" },		  // PROFILER_SCOPE_GROUP_PHYSICS
	{ "rendering", "PROFILER_SCOPE_GROUP_RENDERING" },	  // PROFILER_SCOPE_GROUP_RENDERING
	{ "scene", "PROFILER_SCOPE_GROUP_SCENE" },			  // PROFILER_SCOPE_GROUP_SCENE
	{ "script", "PROFILER_SCOPE_GROUP_SCRIPT" },		  // PROFILER_SCOPE_GROUP_SCRIPT
	{ "streaming", "PROFILER_SCOPE_GROUP_STREAMING" },	  // PROFILER_SCOPE_GROUP_STREAMING
	{ "ui", "PROFILER_SCOPE_GROUP_UI" },				  // PROFILER_SCOPE_GROUP_UI
	{ "vfx", "PROFILER_SCOPE_GROUP_VFX" },				  // PROFILER_SCOPE_GROUP_VFX
	{ "visibility", "PROFILER_SCOPE_GROUP_VISIBILITY" },  // PROFILER_SCOPE_GROUP_VISIBILITY
	{ "wait", "PROFILER_SCOPE_GROUP_WAIT" },			  // PROFILER_SCOPE_GROUP_WAIT
	{ "io", "PROFILER_SCOPE_GROUP_IO" }					  // PROFILER_SCOPE_GROUP_IO
};
static_assert( ARRAYSIZE( s_pProfilerScopeGroupNames ) == PROFILER_SCOPE_NUM_GROUPS, "Size of s_pProfilerScopeGroupNames must be equal to PROFILER_SCOPE_NUM_GROUPS" );

/*
==================
ConvTextToSystemStage
==================
*/
static bool ConvTextToSystemStage( const char* pName, const char*& pSystemStage )
{
	pSystemStage = NULL;
	for ( uint32 systemStageIdx = 0; systemStageIdx < ECS_SYSTEM_NUM_STAGES; ++systemStageIdx )
	{
		if ( !S_Stricmp( pName, s_pEcsSystemStageNames[systemStageIdx].first ) )
		{
			pSystemStage = s_pEcsSystemStageNames[systemStageIdx].second;
			return true;
		}
	}

	return false;
}

/*
==================
ConvTextToProfilerScopeGroup
==================
*/
static bool ConvTextToProfilerScopeGroup( const char* pName, const char*& pProfilerScopeGroup )
{
	pProfilerScopeGroup = NULL;
	for ( uint32 groupIdx = 0; groupIdx < PROFILER_SCOPE_NUM_GROUPS; ++groupIdx )
	{
		if ( !S_Stricmp( pName, s_pProfilerScopeGroupNames[groupIdx].first ) )
		{
			pProfilerScopeGroup = s_pProfilerScopeGroupNames[groupIdx].second;
			return true;
		}
	}

	return false;
}

/*
==================
CEcsCppGenerator::CEcsCppGenerator
==================
*/
CEcsCppGenerator::CEcsCppGenerator()
	: bHasError( false )
{
}

/*
==================
CEcsCppGenerator::Generate
==================
*/
void CEcsCppGenerator::Generate( CEcsStubModule* pEcsStubModule, ecsCppFileType_t cppFileType )
{
	// Write header and include guard
	buffer += "//\n"
			  "// This is automatically generated by the ecscompiler.\n"
			  "// DO NOT modify this manually! Edit the corresponding .ecs files instead!\n"
			  "// Broken Singularity, All Rights Reserved.\n"
			  "//\n\n";
	switch ( cppFileType )
	{
	case ECS_CPP_FILE_TYPE_HEADER: GenerateHeader( pEcsStubModule ); break;
	case ECS_CPP_FILE_TYPE_SOURCE: GenerateSource( pEcsStubModule ); break;
	default:
		AssertMsg( false, "Unknown C++ file type 0x%X", cppFileType );
		break;
	}
}

/*
==================
CEcsCppGenerator::GenerateHeader
==================
*/
void CEcsCppGenerator::GenerateHeader( CEcsStubModule* pEcsStubModule )
{
	buffer += "#pragma once\n";

	// Write usings
	GenerateUsings( pEcsStubModule->GetUsings() );

	// Write components
	GenerateStructs( pEcsStubModule->GetComponents(), ECS_STRUCT_TYPE_COMPONENT );
	GenerateStructs( pEcsStubModule->GetResources(), ECS_STRUCT_TYPE_RESOURCE );

	// Write systems
	GenerateSystems( pEcsStubModule->GetSystems() );

	// Write registrar of the module
	GenerateRegistrar( pEcsStubModule );
}

/*
==================
CEcsCppGenerator::GenerateSource
==================
*/
void CEcsCppGenerator::GenerateSource( CEcsStubModule* pEcsStubModule )
{
	// Generate implementation of EcsReadData functions to read a SENT data into an ECS structs
	GenerateImplementationEcsReadDataFuncs( pEcsStubModule );

	// Generate implementation of ECS factories
	GenerateImplementationEcsFactories( pEcsStubModule );

	// Generate implementation of ECS reflection
	GenerateImplementationEcsReflection( pEcsStubModule );
}

/*
==================
CEcsCppGenerator::GenerateUsings
==================
*/
void CEcsCppGenerator::GenerateUsings( const eastl::vector<CRefPtr<CEcsStubUsing>>& ecsStubUsings )
{
	if ( !ecsStubUsings.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN USING\n" );
		for ( uint32 usingIdx = 0, numUsings = (uint32)ecsStubUsings.size(); usingIdx < numUsings; ++usingIdx )
		{
			CEcsStubUsing* pEcsStubUsing = ecsStubUsings[usingIdx];
			buffer += S_Sprintf( "#include \"%s\"\n", pEcsStubUsing->GetName() );
		}
		buffer += S_Sprintf( "// END USING\n" );
	}
}

/*
==================
CEcsCppGenerator::GenerateComponents
==================
*/
void CEcsCppGenerator::GenerateStructs( const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubDataTypes, ecsStructType_t structsType )
{
	const char* pCppComment		  = NULL;
	const char* pStructPrefix	  = NULL;
	const char* pStructCapsPrefix = NULL;
	switch ( structsType )
	{
	case ECS_STRUCT_TYPE_COMPONENT:
		pCppComment		  = "COMPONENTS";
		pStructPrefix	  = "Component";
		pStructCapsPrefix = "COMPONENT";
		break;

	case ECS_STRUCT_TYPE_RESOURCE:
		pCppComment		  = "RESOURCES";
		pStructPrefix	  = "Resource";
		pStructCapsPrefix = "RESOURCE";
		break;

	default:
		AssertMsg( false, "Unknown struct type 0x%X", structsType );
	}

	if ( !ecsStubDataTypes.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN ECS %s\n", pCppComment );
		for ( uint32 dataTypeIdx = 0, numDataTypes = (uint32)ecsStubDataTypes.size(); dataTypeIdx < numDataTypes; ++dataTypeIdx )
		{
			CEcsStubDataType*										 pEcsStubDataType			  = ecsStubDataTypes[dataTypeIdx];
			const eastl::vector<CRefPtr<CEcsStubDefaultFieldValue>>& ecsStubDefaultFieldValues	  = pEcsStubDataType->GetDefaultFieldValues();
			const eastl::vector<CRefPtr<CEcsStubField>>&			 ecsStubFields				  = pEcsStubDataType->GetFields();
			CEcsStubMetadata*										 pEcsStubDataTypeMetadata	  = pEcsStubDataType->GetMetadata();
			CEcsStubMetadataValue*									 pEcsStubDataTypeNameMetadata = pEcsStubDataTypeMetadata ? pEcsStubDataTypeMetadata->GetValue( ECS_METADATA_TYPE_NAME ) : NULL;
			eastl::string											 ecsDataTypeName			  = pEcsStubDataTypeNameMetadata && pEcsStubDataTypeNameMetadata->HasValue() ? pEcsStubDataTypeNameMetadata->GetValue() : pEcsStubDataType->GetName();
			buffer += S_Sprintf( "struct ecs%s%s_t\n{\n"
								 "\tECS_%s_BODY( \"%s\" )",
								 pStructPrefix, pEcsStubDataType->GetName(),
								 pStructCapsPrefix, ecsDataTypeName.c_str() );

			// Write constructor
			if ( !ecsStubDefaultFieldValues.empty() )
			{
				buffer += S_Sprintf( "\n\tecs%s%s_t()\n", pStructPrefix, pEcsStubDataType->GetName() );
				for ( uint32 defaultFieldValueIdx = 0, numDefaultFieldValues = (uint32)ecsStubDefaultFieldValues.size(); defaultFieldValueIdx < numDefaultFieldValues; ++defaultFieldValueIdx )
				{
					CEcsStubDefaultFieldValue* pEcsStubDefaultFieldValue = ecsStubDefaultFieldValues[defaultFieldValueIdx];
					buffer += S_Sprintf( "\t\t%s %s( %s )\n", defaultFieldValueIdx == 0 ? ":" : ",", pEcsStubDefaultFieldValue->GetName(), pEcsStubDefaultFieldValue->GetValue() );
				}
				buffer += "\t{}";
				if ( !ecsStubFields.empty() )
				{
					buffer += "\n";
				}
			}

			// Write fields
			for ( uint32 fieldIdx = 0, numFields = (uint32)ecsStubFields.size(); fieldIdx < numFields; ++fieldIdx )
			{
				CEcsStubField* pEcsStubField = ecsStubFields[fieldIdx];
				buffer += S_Sprintf( "\n\t%s %s;", pEcsStubField->GetType(), pEcsStubField->GetName() );
			}
			buffer += S_Sprintf( "\n};\n" );

			// Write component factories
			if ( structsType == ECS_STRUCT_TYPE_COMPONENT )
			{
				buffer += S_Sprintf( "IEcsComponentFactory* EcsCreateComponent%sFactory( const CSENTEntityDescComponent& sentComponent );\n", pEcsStubDataType->GetName() );
			}

			if ( dataTypeIdx + 1 < numDataTypes )
			{
				buffer += "\n";
			}
		}
		buffer += S_Sprintf( "// END ECS %s\n", pCppComment );
	}
}

/*
==================
CEcsCppGenerator::GenerateSystems
==================
*/
void CEcsCppGenerator::GenerateSystems( const eastl::vector<CRefPtr<CEcsStubSystem>>& ecsStubSystems )
{
	if ( !ecsStubSystems.empty() )
	{
		buffer += S_Sprintf( "\n// BEGIN ECS SYSTEMS\n" );
		for ( uint32 systemIdx = 0, numSystems = (uint32)ecsStubSystems.size(); systemIdx < numSystems; ++systemIdx )
		{
			CEcsStubSystem*		   pEcsStubSystem			  = ecsStubSystems[systemIdx];
			CEcsStubMetadata*	   pEcsStubSystemMetadata	  = pEcsStubSystem->GetMetadata();
			CEcsStubMetadataValue* pEcsStubSystemNameMetadata = pEcsStubSystemMetadata ? pEcsStubSystemMetadata->GetValue( ECS_METADATA_TYPE_NAME ) : NULL;
			eastl::string		   ecsSystemName			  = pEcsStubSystemNameMetadata && pEcsStubSystemNameMetadata->HasValue() ? pEcsStubSystemNameMetadata->GetValue() : pEcsStubSystem->GetName();

			eastl::string updateParams;
			for ( uint32 fieldAccessType = 0; fieldAccessType < ECS_FIELD_NUM_ACCESS_TYPES; ++fieldAccessType )
			{
				const eastl::vector<CRefPtr<CEcsStubField>>& fields = pEcsStubSystem->GetFields( (ecsFieldAccessType_t)fieldAccessType );
				if ( fieldAccessType != 0 && !fields.empty() && !updateParams.empty() )
				{
					updateParams += ", ";
				}

				for ( uint32 fieldIdx = 0, numFields = (uint32)fields.size(); fieldIdx < numFields; ++fieldIdx )
				{
					CEcsStubField* pField = fields[fieldIdx];
					switch ( fieldAccessType )
					{
					case ECS_FIELD_ACCESS_TYPE_READ: updateParams += S_Sprintf( "const ecsComponent%s_t& %s", pField->GetType(), pField->GetName() ); break;
					case ECS_FIELD_ACCESS_TYPE_WRITE: updateParams += S_Sprintf( "ecsComponent%s_t& %s", pField->GetType(), pField->GetName() ); break;
					case ECS_FIELD_ACCESS_TYPE_READ_OPTIONAL: updateParams += S_Sprintf( "const ecsComponent%s_t* p%s", pField->GetType(), GetStringWithUpperFirstChar( pField->GetName() ).c_str() ); break;
					case ECS_FIELD_ACCESS_TYPE_READ_RESOURCE: updateParams += S_Sprintf( "const ecsResource%s_t& %s", pField->GetType(), pField->GetName() ); break;
					case ECS_FIELD_ACCESS_TYPE_WRITE_OPTIONAL: updateParams += S_Sprintf( "ecsComponent%s_t* p%s", pField->GetType(), GetStringWithUpperFirstChar( pField->GetName() ).c_str() ); break;
					case ECS_FIELD_ACCESS_TYPE_WRITE_RESOURCE: updateParams += S_Sprintf( "ecsResource%s_t& %s", pField->GetType(), pField->GetName() ); break;
					default:
						AssertMsg( false, "Unknown field access 0x%X", fieldAccessType );
						break;
					}

					if ( fieldIdx + 1 < numFields )
					{
						updateParams += ", ";
					}
				}
			}

			buffer += S_Sprintf( "class CEcsSystem%s\n"
								 "{\n"
								 "public:\n"
								 "\tECS_SYSTEM_BODY( \"%s\" )\n"
								 "\tstatic void OnUpdate( CEcsWorld ecsWorld, ecsEntity_t entity%s );\n",
								 pEcsStubSystem->GetName(),
								 ecsSystemName.c_str(),
								 !updateParams.empty() ? S_Sprintf( ", %s", updateParams.c_str() ).c_str() : "" );
			buffer += S_Sprintf( "};\n" );
			if ( systemIdx + 1 < numSystems )
			{
				buffer += "\n";
			}
		}
		buffer += S_Sprintf( "// END ECS SYSTEMS\n" );
	}
}

/*
==================
CEcsCppGenerator::GenerateRegistrar
==================
*/
void CEcsCppGenerator::GenerateRegistrar( CEcsStubModule* pEcsStubModule )
{
	buffer += "\n// Registrar of the module\n";
	buffer += S_Sprintf( "struct ecsModule%s_t\n"
						 "{\n"
						 "%s\n\n"
						 "%s\n"
						 "};\n",
						 pEcsStubModule->GetName(),
						 GenerateRegistrarConstructor( pEcsStubModule ).c_str(),
						 GenerateRegistrarDestructor( pEcsStubModule ).c_str() );
	buffer += S_Sprintf( "void EcsInitReflection_%s();\n", pEcsStubModule->GetName() );
}

/*
==================
CEcsCppGenerator::GenerateRegistrarConstructor
==================
*/
eastl::string CEcsCppGenerator::GenerateRegistrarConstructor( CEcsStubModule* pEcsStubModule )
{
	eastl::string									result;
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubComponents = pEcsStubModule->GetComponents();
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubResources  = pEcsStubModule->GetResources();
	const eastl::vector<CRefPtr<CEcsStubSystem>>&	ecsStubSystems	  = pEcsStubModule->GetSystems();

	// Write the constructor header
	result += S_Sprintf( "\tecsModule%s_t( flecs::world& flecsWorld )\n"
						 "\t{",
						 pEcsStubModule->GetName() );

	// Register components
	if ( !ecsStubComponents.empty() )
	{
		result += "\n\t\t// Register components\n";
		for ( uint32 componentIdx = 0, numComponents = (uint32)ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
		{
			CEcsStubDataType* pEcsStubComponent = ecsStubComponents[componentIdx];
			result += S_Sprintf( "\t\tflecsWorld.component<ecsComponent%s_t>();\n", pEcsStubComponent->GetName() );
		}
	}

	// Register resources
	if ( !ecsStubResources.empty() )
	{
		result += "\n\t\t// Register resources\n";
		for ( uint32 resourceIdx = 0, numResources = (uint32)ecsStubResources.size(); resourceIdx < numResources; ++resourceIdx )
		{
			CEcsStubDataType* pEcsStubResource = ecsStubResources[resourceIdx];
			result += S_Sprintf( "\t\tflecsWorld.component<ecsResource%s_t>();\n", pEcsStubResource->GetName() );
		}
	}

	// Register systems
	if ( !ecsStubSystems.empty() )
	{
		result += S_Sprintf( "\n\t\t// Register systems\n" );
		for ( uint32 systemIdx = 0, numSystems = (uint32)ecsStubSystems.size(); systemIdx < numSystems; ++systemIdx )
		{
			CEcsStubSystem* pEcsStubSystem = ecsStubSystems[systemIdx];
			eastl::string	templateParams;
			eastl::string	readWriteFuncs;
			eastl::string	filterFuncs;
			eastl::string	updateParams;
			eastl::string	callUpdateParams;

			// Write template params and Flecs read/write functions
			for ( uint32 fieldAccessType = 0, globalFieldIdx = 0; fieldAccessType < ECS_FIELD_NUM_ACCESS_TYPES; ++fieldAccessType )
			{
				const eastl::vector<CRefPtr<CEcsStubField>>& fields = pEcsStubSystem->GetFields( (ecsFieldAccessType_t)fieldAccessType );
				if ( fieldAccessType != 0 && !fields.empty() && !updateParams.empty() )
				{
					templateParams += ", ";
					updateParams += ", ";
					callUpdateParams += ", ";
					readWriteFuncs += "\n";
				}

				for ( uint32 fieldIdx = 0, numFields = (uint32)fields.size(); fieldIdx < numFields; ++fieldIdx, ++globalFieldIdx )
				{
					CEcsStubField* pField = fields[fieldIdx];
					switch ( fieldAccessType )
					{
					case ECS_FIELD_ACCESS_TYPE_READ:
						updateParams += S_Sprintf( "const ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams += S_Sprintf( "const ecsComponent%s_t", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.read<ecsComponent%s_t>()", pField->GetType() );
						callUpdateParams += S_Sprintf( "%s", pField->GetName() );
						break;

					case ECS_FIELD_ACCESS_TYPE_READ_OPTIONAL:
					{
						eastl::string fieldName = GetStringWithUpperFirstChar( pField->GetName() );
						updateParams += S_Sprintf( "const ecsComponent%s_t* p%s", pField->GetType(), fieldName.c_str() );
						templateParams += S_Sprintf( "const ecsComponent%s_t*", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.read<ecsComponent%s_t*>()", pField->GetType() );
						callUpdateParams += S_Sprintf( "p%s", fieldName.c_str() );
						break;
					}

					case ECS_FIELD_ACCESS_TYPE_READ_RESOURCE:
						updateParams += S_Sprintf( "const ecsResource%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams += S_Sprintf( "const ecsResource%s_t", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.term_at( %i ).singleton()\n"
													 "\t\t\t.read<ecsResource%s_t>()",
													 globalFieldIdx, pField->GetType() );
						callUpdateParams += S_Sprintf( "%s", pField->GetName() );
						break;

					case ECS_FIELD_ACCESS_TYPE_WRITE:
						updateParams += S_Sprintf( "ecsComponent%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams += S_Sprintf( "ecsComponent%s_t", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.write<ecsComponent%s_t>()", pField->GetType() );
						callUpdateParams += S_Sprintf( "%s", pField->GetName() );
						break;

					case ECS_FIELD_ACCESS_TYPE_WRITE_OPTIONAL:
					{
						eastl::string fieldName = GetStringWithUpperFirstChar( pField->GetName() );
						updateParams += S_Sprintf( "ecsComponent%s_t* p%s", pField->GetType(), fieldName.c_str() );
						templateParams += S_Sprintf( "ecsComponent%s_t*", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.write<ecsComponent%s_t*>()", pField->GetType() );
						callUpdateParams += S_Sprintf( "p%s", fieldName.c_str() );
						break;
					}

					case ECS_FIELD_ACCESS_TYPE_WRITE_RESOURCE:
						updateParams += S_Sprintf( "ecsResource%s_t& %s", pField->GetType(), pField->GetName() );
						templateParams += S_Sprintf( "ecsResource%s_t", pField->GetType() );
						readWriteFuncs += S_Sprintf( "\t\t\t.term_at( %i ).singleton()\n"
													 "\t\t\t.write<ecsResource%s_t>()",
													 globalFieldIdx, pField->GetType() );
						callUpdateParams += S_Sprintf( "%s", pField->GetName() );
						break;

					default:
						AssertMsg( false, "Unknown field access 0x%X", fieldAccessType );
						break;
					}

					if ( fieldIdx + 1 < numFields )
					{
						templateParams += ", ";
						updateParams += ", ";
						callUpdateParams += ", ";
						readWriteFuncs += "\n";
					}
				}
			}
			if ( !readWriteFuncs.empty() )
			{
				readWriteFuncs += "\n";
			}

			// Write Flecs filters
			for ( uint32 systemFilterType = 0; systemFilterType < ECS_SYSTEM_NUM_FILTER_TYPES; ++systemFilterType )
			{
				const eastl::vector<CRefPtr<CEcsStubSystemFilter>>& filters = pEcsStubSystem->GetFilters( (ecsSystemFilterType_t)systemFilterType );
				if ( systemFilterType != 0 && !filters.empty() && !filterFuncs.empty() )
				{
					filterFuncs += "\n";
				}

				for ( uint32 filterIdx = 0, numFilters = (uint32)filters.size(); filterIdx < numFilters; ++filterIdx )
				{
					CEcsStubSystemFilter* pEcsSystemFilter = filters[filterIdx];
					switch ( systemFilterType )
					{
					case ECS_SYSTEM_FILTER_TYPE_INCLUDE: filterFuncs += S_Sprintf( "\t\t\t.with<ecsComponent%s_t>()", pEcsSystemFilter->GetName() ); break;
					case ECS_SYSTEM_FILTER_TYPE_EXCLUDE: filterFuncs += S_Sprintf( "\t\t\t.without<ecsComponent%s_t>()", pEcsSystemFilter->GetName() ); break;
					default:
						AssertMsg( false, "Unknown system filter 0x%X", systemFilterType );
						break;
					}

					if ( filterIdx + 1 < numFilters )
					{
						filterFuncs += "\n";
					}
				}
			}
			if ( !filterFuncs.empty() )
			{
				filterFuncs += "\n";
			}

			// Register the system
			CEcsStubMetadata*	   pEcsStubSystemMetadata			   = pEcsStubSystem->GetMetadata();
			CEcsStubMetadataValue* pEcsStubSystemMetadataProfilerGroup = pEcsStubSystemMetadata ? pEcsStubSystemMetadata->GetValue( ECS_METADATA_TYPE_PROFILER_GROUP ) : NULL;
			const char*			   pProfilerScopeGroupName			   = NULL;
			if ( pEcsStubSystemMetadataProfilerGroup && S_Strlen( pEcsStubSystemMetadataProfilerGroup->GetValue() ) > 0 && !ConvTextToProfilerScopeGroup( pEcsStubSystemMetadataProfilerGroup->GetValue(), pProfilerScopeGroupName ) )
			{
				Error( "%s: Unknown profiler group '%s'", pEcsStubSystemMetadataProfilerGroup->GetValueContext().ToString().c_str(), pEcsStubSystemMetadataProfilerGroup->GetValue() );
				bHasError = true;
			}

			CEcsStubMetadataValue* pEcsStubSystemMetadataStage = pEcsStubSystemMetadata ? pEcsStubSystemMetadata->GetValue( ECS_METADATA_TYPE_STAGE ) : NULL;
			const char*			   pSystemStageName			   = s_pEcsSystemStageNames[ECS_SYSTEM_STAGE_ONUPDATE].second;
			if ( pEcsStubSystemMetadataStage && S_Strlen( pEcsStubSystemMetadataStage->GetValue() ) > 0 && !ConvTextToSystemStage( pEcsStubSystemMetadataStage->GetValue(), pSystemStageName ) )
			{
				Error( "%s: Unknown system stage '%s'", pEcsStubSystemMetadataStage->GetValueContext().ToString().c_str(), pEcsStubSystemMetadataStage->GetValue() );
				bHasError = true;
			}

			result += S_Sprintf( "\t\tflecsWorld.system<%s>()\n"
								 "\t\t\t.kind( flecs::%s )\n"
								 "%s"
								 "%s"
								 "\t\t\t.each( []( flecs::entity entity%s )\n"
								 "\t\t\t{\n"
								 "%s"
								 "\t\t\t\tCEcsSystem%s::OnUpdate( entity.world(), entity%s );\n"
								 "\t\t\t} );\n",
								 templateParams.c_str(),
								 pSystemStageName,
								 readWriteFuncs.c_str(),
								 filterFuncs.c_str(),
								 !updateParams.empty() ? S_Sprintf( ", %s", updateParams.c_str() ).c_str() : "",
								 pProfilerScopeGroupName ? S_Sprintf( "\t\t\t\tPROFILER_SCOPE_FUNC_GROUP( %s );\n", pProfilerScopeGroupName ).c_str() : "",
								 pEcsStubSystem->GetName(),
								 !callUpdateParams.empty() ? S_Sprintf( ", %s", callUpdateParams.c_str() ).c_str() : "" );
			if ( systemIdx + 1 < numSystems )
			{
				result += "\n";
			}
		}
	}

	// Write the constructor bottom
	if ( !ecsStubComponents.empty() || !ecsStubResources.empty() || !ecsStubSystems.empty() )
	{
		result += "\t";
	}
	result += "}";
	return result;
}

/*
==================
CEcsCppGenerator::GenerateRegistrarDestructor
==================
*/
eastl::string CEcsCppGenerator::GenerateRegistrarDestructor( CEcsStubModule* pEcsStubModule )
{
	eastl::string									result;
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubComponents = pEcsStubModule->GetComponents();
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubResources  = pEcsStubModule->GetResources();
	const eastl::vector<CRefPtr<CEcsStubSystem>>&	ecsStubSystems	  = pEcsStubModule->GetSystems();

	// Write the destructor header
	result += S_Sprintf( "\t~ecsModule%s_t()\n"
						 "\t{",
						 pEcsStubModule->GetName() );

	// Write the destructor bottom
	result += "}";
	return result;
}

/*
==================
CEcsCppGenerator::GenerateImplementationEcsReadDataFuncs
==================
*/
void CEcsCppGenerator::GenerateImplementationEcsReadDataFuncs( CEcsStubModule* pEcsStubModule )
{
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubComponents = pEcsStubModule->GetComponents();
	for ( uint32 componentIdx = 0, numComponents = (uint32)ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
	{
		eastl::string								 sentReadDataFields;
		CEcsStubDataType*							 pEcsStubComponent = ecsStubComponents[componentIdx];
		const eastl::vector<CRefPtr<CEcsStubField>>& ecsStubFields	   = pEcsStubComponent->GetFields();
		for ( uint32 varIdx = 0, numVars = (uint32)ecsStubFields.size(); varIdx < numVars; ++varIdx )
		{
			CEcsStubField*	  pEcsStubField			= ecsStubFields[varIdx];
			CEcsStubMetadata* pEcsStubFieldMetadata = pEcsStubField->GetMetadata();
			if ( pEcsStubFieldMetadata && pEcsStubFieldMetadata->HasValue( ECS_METADATA_TYPE_SERIALIZE ) )
			{
				CEcsStubDefaultFieldValue* pEcsStubDefaultFieldValue = pEcsStubComponent->FindDefaultFieldValue( pEcsStubField->GetName() );
				CEcsStubMetadataValue*	   pEcsStubFieldNameMetadata = pEcsStubFieldMetadata->GetValue( ECS_METADATA_TYPE_NAME );
				eastl::string			   fieldName				 = pEcsStubFieldNameMetadata && pEcsStubFieldNameMetadata->HasValue() ? pEcsStubFieldNameMetadata->GetValue() : "";
				if ( fieldName.empty() )
				{
					fieldName = pEcsStubField->GetName();
				}

				if ( !sentReadDataFields.empty() )
				{
					sentReadDataFields += "\n\n";
				}

				sentReadDataFields += S_Sprintf( "\tCSENTEntityDescVar*\t\tpSENTVar_%s = sentComponent.GetVar( \"%s\" );\n", pEcsStubField->GetName(), fieldName.c_str() );
				sentReadDataFields += S_Sprintf( "\tif ( pSENTVar_%s )\n", pEcsStubField->GetName() );
				sentReadDataFields += "\t{\n";
				sentReadDataFields += S_Sprintf( "\t\tEcsReadData<%s>( component.%s, *pSENTVar_%s%s );\n",
												 pEcsStubField->GetType(), pEcsStubField->GetName(), pEcsStubField->GetName(),
												 pEcsStubDefaultFieldValue ? S_Sprintf( ", %s", pEcsStubDefaultFieldValue->GetValue() ).c_str() : "" );
				sentReadDataFields += "\t}";
				if ( pEcsStubDefaultFieldValue )
				{
					sentReadDataFields += "\n\telse\n";
					sentReadDataFields += "\t{\n";
					sentReadDataFields += S_Sprintf( "\t\tcomponent.%s = %s;\n", pEcsStubField->GetName(), pEcsStubDefaultFieldValue->GetValue() );
					sentReadDataFields += "\t}";
				}
			}
		}

		if ( !sentReadDataFields.empty() )
		{
			buffer += "\n/*\n";
			buffer += "==================\n";
			buffer += "EcsReadData\n";
			buffer += "==================\n";
			buffer += "*/\n";
			buffer += S_Sprintf( "static void EcsReadData( const CSENTEntityDescComponent& sentComponent, ecsComponent%s_t& component )\n"
								 "{\n"
								 "\tPROFILER_SCOPE_FUNC_GROUP( PROFILER_SCOPE_GROUP_IO );\n"
								 "%s\n"
								 "}\n",
								 pEcsStubComponent->GetName(), sentReadDataFields.c_str() );
		}
	}
}

/*
==================
CEcsCppGenerator::GenerateImplementationEcsFactories
==================
*/
void CEcsCppGenerator::GenerateImplementationEcsFactories( CEcsStubModule* pEcsStubModule )
{
	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubComponents = pEcsStubModule->GetComponents();
	for ( uint32 componentIdx = 0, numComponents = (uint32)ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
	{
		bool										 bHasSerializableField = false;
		CEcsStubDataType*							 pEcsStubComponent	   = ecsStubComponents[componentIdx];
		const eastl::vector<CRefPtr<CEcsStubField>>& ecsStubFields		   = pEcsStubComponent->GetFields();
		for ( uint32 varIdx = 0, numVars = (uint32)ecsStubFields.size(); varIdx < numVars; ++varIdx )
		{
			CEcsStubField*	  pEcsStubField			= ecsStubFields[varIdx];
			CEcsStubMetadata* pEcsStubFieldMetadata = pEcsStubField->GetMetadata();
			if ( pEcsStubFieldMetadata && pEcsStubFieldMetadata->HasValue( ECS_METADATA_TYPE_SERIALIZE ) )
			{
				bHasSerializableField = true;
				break;
			}
		}

		buffer += "\n/*\n";
		buffer += "==================\n";
		buffer += S_Sprintf( "EcsCreateComponent%sFactory\n", pEcsStubComponent->GetName() );
		buffer += "==================\n";
		buffer += "*/\n";
		buffer += S_Sprintf( "IEcsComponentFactory* EcsCreateComponent%sFactory( const CSENTEntityDescComponent& sentComponent )\n"
							 "{\n"
							 "\treturn new CEcsComponentFactory<ecsComponent%s_t, %s>( sentComponent );\n"
							 "}\n",
							 pEcsStubComponent->GetName(), pEcsStubComponent->GetName(), bHasSerializableField ? "EcsReadData" : "NULL" );
	}
}

/*
==================
CEcsCppGenerator::GenerateImplementationEcsReflection
==================
*/
void CEcsCppGenerator::GenerateImplementationEcsReflection( CEcsStubModule* pEcsStubModule )
{
	buffer += "\n/*\n";
	buffer += "==================\n";
	buffer += S_Sprintf( "EcsInitReflection_%s\n", pEcsStubModule->GetName() );
	buffer += "==================\n";
	buffer += "*/\n";
	buffer += S_Sprintf( "void EcsInitReflection_%s()\n{", pEcsStubModule->GetName() );

	const eastl::vector<CRefPtr<CEcsStubDataType>>& ecsStubComponents = pEcsStubModule->GetComponents();
	if ( !ecsStubComponents.empty() )
	{
		buffer += "\n\t// Register component types\n";
		buffer += "\tCEcsComponentTypes&\t\tecsComponentTypes = Game()->GetEcsComponentTypes();\n";
		for ( uint32 componentIdx = 0, numComponents = (uint32)ecsStubComponents.size(); componentIdx < numComponents; ++componentIdx )
		{
			CEcsStubDataType* pEcsStubComponent = ecsStubComponents[componentIdx];
			buffer += S_Sprintf( "\tecsComponentTypes.RegisterType( ecsComponent%s_t::GetComponentName(), EcsCreateComponent%sFactory );\n", pEcsStubComponent->GetName(), pEcsStubComponent->GetName() );
		}
	}

	buffer += "};";
}
