#pragma once
#undef PLATFORM_USE__ALIGNED_MALLOC
#undef PLATFORM_IS_ANSI_MALLOC_THREADSAFE
#undef PLATFORM_SUPPORTS_MIMALLOC
#undef PLATFORM_USE_SDL

#define PLATFORM_USE__ALIGNED_MALLOC	   1
#define PLATFORM_IS_ANSI_MALLOC_THREADSAFE 1
#define PLATFORM_SUPPORTS_MIMALLOC		   PLATFORM_64BIT
#define PLATFORM_USE_SDL				   1
