#ifndef BUILD_H
#define BUILD_H

#ifndef PLATFORM_32BIT
	#define PLATFORM_32BIT		0
#endif // !PLATFORM_32BIT

#ifndef PLATFORM_64BIT
	#define PLATFORM_64BIT		0
#endif // !PLATFORM_64BIT

#ifndef ENABLE_ASSERT
	#define ENABLE_ASSERT		!RETAIL
#endif // !ENABLE_ASSERT

#ifndef ENABLE_ENSURE
	#define ENABLE_ENSURE		!RETAIL
#endif // !ENABLE_ENSURE

#ifndef ENABLE_LOGGING
	#define ENABLE_LOGGING		!RETAIL
#endif // !ENABLE_LOGGING

#ifndef ENABLE_PROFILING
	#define ENABLE_PROFILING	!RETAIL
#endif // !ENABLE_PROFILING

#endif // !BUILD_H