#pragma once
#define ENGINE_GOLDDATE					45113	// 45113 - Jul 07 2024 (Singularity Engine development start), used for generate a build number by TBuildNumber
#define ENGINE_VERSION_MAJOR			0
#define ENGINE_VERSION_MINOR			1
#define ENGINE_VERSION_PATCH			0
#define ENGINE_BRANCH_NAME				GIT_BRANCH
#define ENGINE_VERSION					PACK_VERSION( ENGINE_VERSION_MAJOR, ENGINE_VERSION_MINOR, ENGINE_VERSION_PATCH )
#define ENGINE_VERSION_STRING			STRINGIFY( ENGINE_VERSION_MAJOR ) "." STRINGIFY( ENGINE_VERSION_MINOR ) "." STRINGIFY( ENGINE_VERSION_PATCH ) "-" ENGINE_BRANCH_NAME
