#include "pch_shadercompiler.h"
#include "modelsystem/modeltypes.h"
#include "tools/shadercompiler/shadercompiler_cppgenerator.h"

/*
==================
CShaderCompilerCppGenerator::Generate
==================
*/
void CShaderCompilerCppGenerator::Generate( const shader_t& shader )
{
	// Generate C++ header
	buffer += "//\n";
	buffer += "// This is automatically generated by shadercompiler\n";
	buffer += "// DO NOT modify this manually! Edit the corresponding .shader instead!\n";
	buffer += "// Copyright (C) 2024-2026 Broken Singularity\n";
	buffer += "//\n\n";

	// Generate class name from base name of shader source file and the one type
	eastl::string className;
	{
		// Get base name from shader source file
		eastl::string fileBaseName;
		S_GetFileBaseName( shader.source, fileBaseName, false );

		// Get class name
		className = S_Sprintf( "C_%s_%s_Index", fileBaseName.c_str(), ConvShaderTypeToString( shader.type ) );
	}

	// Generate C++ class header
	buffer += S_Sprintf( "class %s\n", className.c_str() );
	buffer += "{\n";

	// Generate for each shader flag a var and set function of the one
	for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
	{
		const shaderFlag_t& shaderFlag = shader.flags[index];
		buffer += "\t//\n";
		buffer += S_Sprintf( "\t// Shader flag '%s' with range [%i;%i]\n", shaderFlag.name.c_str(), shaderFlag.minValue, shaderFlag.maxValue );
		buffer += "\t//\n";
		GenerateVar( shaderFlag );
		buffer += "\n\n";
	}

	// Generate a helper that maps a model vertex type to this shader's local vertex factory index
	if ( !shader.vertexFactories.empty() )
	{
		buffer += "\t//\n";
		buffer += "\t// Map a model vertex type to this shader's local vertex factory index (INVALID_INDEX if unsupported)\n";
		buffer += "\t//\n";
		GenerateRemapVertexFactories( shader );
		buffer += "\n\n";
	}

	// Generate class constructor
	buffer += "\t//\n";
	buffer += "\t// Class constructor\n";
	buffer += "\t//\n";
	GenerateConstructor( className.c_str(), shader );
	buffer += "\n\n";

	// Generate GetIndex function
	buffer += "\t//\n";
	buffer += "\t// Calculate shader index for the flags combination\n";
	buffer += "\t//\n";
	GenerateGetIndexFunc( shader );
	buffer += "\n";

	// Generate C++ class footer
	buffer += "};\n";
}

/*
==================
CShaderCompilerCppGenerator::GenerateVar
==================
*/
void CShaderCompilerCppGenerator::GenerateVar( const shaderFlag_t& shaderFlag )
{
	// Generate variables
	buffer += "private:\n";
	buffer += S_Sprintf( "\tuint32 %s;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += S_Sprintf( "\tbool b%s;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";

	// Generate set function
	buffer += "public:\n";

	buffer += S_Sprintf( "\tvoid Set%s( uint32 value )\n", shaderFlag.name.c_str() );
	buffer += "\t{\n";
	buffer += S_Sprintf( "\t\tAssert( value >= %i && value <= %i );\n", shaderFlag.minValue, shaderFlag.maxValue );
	buffer += S_Sprintf( "\t\t%s = value;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += S_Sprintf( "\t\tb%s = true;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";
	buffer += "\t}";
}

/*
==================
CShaderCompilerCppGenerator::GenerateVar
==================
*/
void CShaderCompilerCppGenerator::GenerateConstructor( const char* pClassName, const shader_t& shader )
{
	buffer += "public:\n";
	buffer += S_Sprintf( "\t%s()\n", pClassName );
	if ( !shader.flags.empty() )
	{
		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "\t\t%s", index == 0 ? ": " : ", " );
			buffer += S_Sprintf( "%s( %i )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? shaderFlag.defaultValue : shaderFlag.minValue );
			buffer += "#if DEBUG\n";
			buffer += S_Sprintf( "\t\t, b%s( %s )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? "true" : "false" );
			buffer += "#endif // DEBUG\n";
		}
	}
	buffer += "\t{}";
}

/*
==================
CShaderCompilerCppGenerator::GenerateGetIndexFunc
==================
*/
void CShaderCompilerCppGenerator::GenerateGetIndexFunc( const shader_t& shader )
{
	buffer += "public:\n";
	buffer += "\tuint32 GetIndex() const\n";
	buffer += "\t{\n";

	// Generate assert to make sure that we are setting all of the combination vars
	if ( !shader.flags.empty() )
	{
		buffer += "\t\t// Asserts to make sure that we are setting all of the combination vars\n";
		buffer += "#if DEBUG\n";
		buffer += S_Sprintf( "\t\tbool bAllVarsDefined = " );

		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "b%s", shaderFlag.name.c_str() );
			if ( index + 1 < count )
			{
				buffer += " && ";
			}
			else
			{
				buffer += ";\n";
			}
		}

		buffer += "\t\tAssert( bAllVarsDefined );\n";
		buffer += "#endif // DEBUG\n";
	}

	// Generate code of calculation shader index for the flags combination
	buffer += "\t\treturn ";
	if ( !shader.flags.empty() )
	{
		uint32 scale = 1;
		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "( %i * %s ) + ", scale, shaderFlag.name.c_str() );
			scale *= shaderFlag.maxValue - shaderFlag.minValue + 1;
		}
	}

	buffer += "0;\n\t}";
}

/*
==================
CShaderCompilerCppGenerator::GenerateRemapVertexFactories
==================
*/
void CShaderCompilerCppGenerator::GenerateRemapVertexFactories( const shader_t& shader )
{
	// Build the remap table: modelVertexType_t -> shader's local vertex factory index (INVALID_INDEX if unsupported).
	uint32 vertexFactoryRemap[MODEL_VERTEX_NUM_TYPES + 1];	// +1 for 'none' vertex factory
	Mem_Memset( vertexFactoryRemap, (uint8)INVALID_INDEX, ( MODEL_VERTEX_NUM_TYPES + 1 ) * sizeof( uint32 ) );
	for ( uint32 index = 0, count = (uint32)shader.vertexFactories.size(); index < count; ++index )
	{
		const vertexFactory_t* pVertexFactory = shader.vertexFactories[index];
		if ( pVertexFactory == &vertexFactory_t::s_none )
		{
			vertexFactoryRemap[MODEL_VERTEX_NUM_TYPES] = index;
			continue;
		}

		Assert( pVertexFactory->index < MODEL_VERTEX_NUM_TYPES );
		vertexFactoryRemap[pVertexFactory->index] = index;
	}

	// Begin function `SetVertexFactory`
	const char* pVertexFactoryFlagName = ConvShaderSystemFlagToString( SHADER_SYSTEM_FLAG_VERTEXFACTORY );
	buffer += "public:\n";
	buffer += "\tvoid SetVertexFactory( IVertexFactory* pVertexFactory )\n";
	buffer += "\t{\n";
	buffer += "\t\tstatic const uint32 s_vertexFactoryRemap[MODEL_VERTEX_NUM_TYPES] = { ";
	for ( uint32 index = 0; index < MODEL_VERTEX_NUM_TYPES; ++index )
	{
		uint32 vertexFactoryIndex = vertexFactoryRemap[index];
		buffer += vertexFactoryIndex != INVALID_INDEX ? S_Sprintf( "%i", vertexFactoryIndex ) : "(uint32)INVALID_INDEX";
		if ( index + 1 < MODEL_VERTEX_NUM_TYPES )
		{
			buffer += ", ";
		}
	}
	buffer += " };\n";

	// Generate section to select being drawn without any vertex factory
	buffer += "\t\tif ( !pVertexFactory )\n";
	buffer += "\t\t{\n";
	if ( vertexFactoryRemap[MODEL_VERTEX_NUM_TYPES] != (uint32)INVALID_INDEX )
	{
		buffer += S_Sprintf( "\t\t\tSet%s( %i );\n", pVertexFactoryFlagName, vertexFactoryRemap[MODEL_VERTEX_NUM_TYPES] );
	}
	else
	{
		buffer += "\t\t\tAssertMsg( false, \"This shader doesn't support being drawn without a vertex factory\" );\n";
		buffer += S_Sprintf( "\t\t\tSet%s( 0 );\n", pVertexFactoryFlagName );
	}
	buffer += "\t\t\treturn;\n";
	buffer += "\t\t}\n\n";

	// Generate section to set a vertex factory by a model vertex type
	buffer += "\t\tmodelVertexType_t vertexType = pVertexFactory->GetVertexType();\n";
	buffer += "\t\tAssert( vertexType < MODEL_VERTEX_NUM_TYPES && s_vertexFactoryRemap[(uint32)vertexType] != INVALID_INDEX );\n";
	buffer += S_Sprintf( "\t\tSet%s( s_vertexFactoryRemap[vertexType] );\n", pVertexFactoryFlagName );

	// End function `SetVertexFactory`
	buffer += "\t}";
}
