#include "pch_shadercompiler.h"
#include "tools/shadercompiler/shadercompiler_cppgenerator.h"

/*
==================
CShaderCompilerCppGenerator::Generate
==================
*/
void CShaderCompilerCppGenerator::Generate( const shader_t& shader )
{
	// Generate C++ header
	buffer += "//\n";
	buffer += "// This is automatically generated by shadercompiler\n";
	buffer += "// DO NOT modify this manually! Edit the corresponding .shader instead!\n";
	buffer += "// Copyright (C) 2024-2026 Broken Singularity\n";
	buffer += "//\n\n";

	// Generate class name from base name of shader source file and the one type
	eastl::string className;
	{
		// Convert shader type to string
		const char* pShaderTypeName = "";
		ConvShaderTypeToString( shader.type, pShaderTypeName );

		// Get base name from shader source file
		eastl::string fileBaseName;
		S_GetFileBaseName( shader.source, fileBaseName, false );

		// Get class name
		className = S_Sprintf( "C_%s_%s_Index", fileBaseName.c_str(), pShaderTypeName );
	}

	// Generate C++ class header
	buffer += S_Sprintf( "class %s\n", className.c_str() );
	buffer += "{\n";

	// Generate for each shader flag a var and set function of the one
	for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
	{
		const shaderFlag_t& shaderFlag = shader.flags[index];
		buffer += "\t//\n";
		buffer += S_Sprintf( "\t// Shader flag '%s' with range [%i;%i]\n", shaderFlag.name.c_str(), shaderFlag.minValue, shaderFlag.maxValue );
		buffer += "\t//\n";
		GenerateVar( shaderFlag );
		buffer += "\n\n";
	}

	// Generate class constructor
	buffer += "\t//\n";
	buffer += "\t// Class constructor\n";
	buffer += "\t//\n";
	GenerateConstructor( className.c_str(), shader );
	buffer += "\n\n";

	// Generate GetIndex function
	buffer += "\t//\n";
	buffer += "\t// Calculate shader index for the flags combination\n";
	buffer += "\t//\n";
	GenerateGetIndexFunc( shader );
	buffer += "\n";

	// Generate C++ class footer
	buffer += "};\n";
}

/*
==================
CShaderCompilerCppGenerator::GenerateVar
==================
*/
void CShaderCompilerCppGenerator::GenerateVar( const shaderFlag_t& shaderFlag )
{
	// Generate variables
	buffer += "private:\n";
	buffer += S_Sprintf( "\tuint32 %s;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += S_Sprintf( "\tbool b%s;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";

	// Generate set function
	buffer += "public:\n";

	// Uint32 version
	buffer += S_Sprintf( "\tvoid Set%s( uint32 value )\n", shaderFlag.name.c_str() );
	buffer += "\t{\n";
	buffer += S_Sprintf( "\t\tAssert( value >= %i && value <= %i );\n", shaderFlag.minValue, shaderFlag.maxValue );
	buffer += S_Sprintf( "\t\t%s = value;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += S_Sprintf( "\t\tb%s = true;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";
	buffer += "\t}";

	// Bool version (only if 0 and 1 in our range)
	if ( 0 >= shaderFlag.minValue && 0 <= shaderFlag.maxValue && 1 >= shaderFlag.minValue && 1 <= shaderFlag.maxValue )
	{
		buffer += S_Sprintf( "\n\n\tvoid Set%s( bool bValue )\n", shaderFlag.name.c_str() );
		buffer += "\t{\n";
		buffer += S_Sprintf( "\t\t%s = bValue ? 1 : 0;\n", shaderFlag.name.c_str() );
		buffer += "#if DEBUG\n";
		buffer += S_Sprintf( "\t\tb%s = true;\n", shaderFlag.name.c_str() );
		buffer += "#endif // DEBUG\n";
		buffer += "\t}";
	}
}

/*
==================
CShaderCompilerCppGenerator::GenerateVar
==================
*/
void CShaderCompilerCppGenerator::GenerateConstructor( const char* pClassName, const shader_t& shader )
{
	buffer += "public:\n";
	buffer += S_Sprintf( "\t%s()\n", pClassName );
	if ( !shader.flags.empty() )
	{
		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "\t\t%s", index == 0 ? ": " : ", " );
			buffer += S_Sprintf( "%s( %i )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? shaderFlag.defaultValue : shaderFlag.minValue );
			buffer += "#if DEBUG\n";
			buffer += S_Sprintf( "\t\t, b%s( %s )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? "true" : "false" );
			buffer += "#endif // DEBUG\n";
		}
	}
	buffer += "\t{}";
}

/*
==================
CShaderCompilerCppGenerator::GenerateGetIndexFunc
==================
*/
void CShaderCompilerCppGenerator::GenerateGetIndexFunc( const shader_t& shader )
{
	buffer += "public:\n";
	buffer += "\tuint32 GetIndex() const\n";
	buffer += "\t{\n";

	// Generate assert to make sure that we are setting all of the combination vars
	if ( !shader.flags.empty() )
	{
		buffer += "\t\t// Asserts to make sure that we are setting all of the combination vars\n";
		buffer += "#if DEBUG\n";
		buffer += S_Sprintf( "\t\tbool bAllVarsDefined = " );

		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "b%s", shaderFlag.name.c_str() );
			if ( index + 1 < count )
			{
				buffer += " && ";
			}
			else
			{
				buffer += ";\n";
			}
		}

		buffer += "\t\tAssert( bAllVarsDefined );\n";
		buffer += "#endif // DEBUG\n";
	}

	// Generate code of calculation shader index for the flags combination
	buffer += "\t\treturn ";
	if ( !shader.flags.empty() )
	{
		uint32 scale = 1;
		for ( uint32 index = 0, count = (uint32)shader.flags.size(); index < count; ++index )
		{
			const shaderFlag_t& shaderFlag = shader.flags[index];
			buffer += S_Sprintf( "( %i * %s ) + ", scale, shaderFlag.name.c_str() );
			scale *= shaderFlag.maxValue - shaderFlag.minValue + 1;
		}
	}

	buffer += "0;\n\t}";
}